package com.reporting.service;

import com.reporting.dto.Enums.ColType;
import java.time.LocalDate;

/**
 * Utility class for computing date boundary pairs used in conditional
 * aggregation
 * {@code CASE WHEN} clauses generated by {@link SqlGeneratorService}.
 *
 * <p>
 * The {@link #getPeriodBoundaries} overload that accepts a {@code rollingGrain}
 * parameter is the preferred entry point. The single-argument overload
 * delegates
 * to it with a {@code null} grain (defaults to WEEK) for backward
 * compatibility.
 * </p>
 */
public class DateUtils {

    // ─── public API ───────────────────────────────────────────────────────────

    /**
     * Backward-compatible overload: delegates to
     * {@link #getPeriodBoundaries(LocalDate, ColType, int, Integer, String)} with
     * a {@code null} grain (= WEEK for ROLLING columns).
     */
    public static LocalDate[] getPeriodBoundaries(LocalDate refDate, ColType colType, int offset, Integer rollingN) {
        return getPeriodBoundaries(refDate, colType, offset, rollingN, null);
    }

    /**
     * Computes the inclusive {@code [start, end]} date pair for a given column's
     * time window relative to {@code refDate}.
     *
     * <p>
     * For {@code ROLLING} columns the {@code rollingGrain} parameter drives
     * the unit of the lookback window:
     * </p>
     * <ul>
     * <li>{@code "DAY"} — {@code start = refDate - N days + 1 day}</li>
     * <li>{@code "WEEK"} — {@code start = refDate - N weeks + 1 day} (default)</li>
     * <li>{@code "MONTH"} — {@code start = refDate - N months + 1 day}</li>
     * </ul>
     *
     * @param refDate      the reporting reference date (anchor of all calculations)
     * @param colType      the column's time-window type (WEEK, MTD, YTD, ROLLING)
     * @param offset       period shift (negative = past, 0 = current, positive =
     *                     future)
     * @param rollingN     number of grain-units in the rolling window (ROLLING
     *                     only)
     * @param rollingGrain one of {@code "DAY"}, {@code "WEEK"}, {@code "MONTH"};
     *                     {@code null} → defaults to {@code "WEEK"}
     * @return a two-element array: {@code [startDate, endDate]} (both inclusive)
     * @throws IllegalArgumentException if {@code colType} is unsupported
     */
    public static LocalDate[] getPeriodBoundaries(
            LocalDate refDate,
            ColType colType,
            int offset,
            Integer rollingN,
            String rollingGrain) {
        return TimeWindowResolver.resolveBoundaries(refDate, colType, offset, rollingN, rollingGrain);
    }
}
