package com.reporting.service;

import com.reporting.dto.Enums.ColType;
import java.time.LocalDate;
import java.time.DayOfWeek;
import java.time.temporal.TemporalAdjusters;

/**
 * Utility class for computing date boundary pairs used in conditional aggregation
 * {@code CASE WHEN} clauses generated by {@link SqlGeneratorService}.
 *
 * <p>The {@link #getPeriodBoundaries} overload that accepts a {@code rollingGrain}
 * parameter is the preferred entry point. The single-argument overload delegates
 * to it with a {@code null} grain (defaults to WEEK) for backward compatibility.</p>
 */
public class DateUtils {

    // ─── public API ───────────────────────────────────────────────────────────

    /**
     * Backward-compatible overload: delegates to
     * {@link #getPeriodBoundaries(LocalDate, ColType, int, Integer, String)} with
     * a {@code null} grain (= WEEK for ROLLING columns).
     */
    public static LocalDate[] getPeriodBoundaries(LocalDate refDate, ColType colType, int offset, Integer rollingN) {
        return getPeriodBoundaries(refDate, colType, offset, rollingN, null);
    }

    /**
     * Computes the inclusive {@code [start, end]} date pair for a given column's
     * time window relative to {@code refDate}.
     *
     * <p>For {@code ROLLING} columns the {@code rollingGrain} parameter drives
     * the unit of the lookback window:</p>
     * <ul>
     *   <li>{@code "DAY"}   — {@code start = refDate - N days + 1 day}</li>
     *   <li>{@code "WEEK"}  — {@code start = refDate - N weeks + 1 day} (default)</li>
     *   <li>{@code "MONTH"} — {@code start = refDate - N months + 1 day}</li>
     * </ul>
     *
     * @param refDate     the reporting reference date (anchor of all calculations)
     * @param colType     the column's time-window type (WEEK, MTD, YTD, ROLLING)
     * @param offset      period shift (negative = past, 0 = current, positive = future)
     * @param rollingN    number of grain-units in the rolling window (ROLLING only)
     * @param rollingGrain one of {@code "DAY"}, {@code "WEEK"}, {@code "MONTH"};
     *                    {@code null} → defaults to {@code "WEEK"}
     * @return a two-element array: {@code [startDate, endDate]} (both inclusive)
     * @throws IllegalArgumentException if {@code colType} is unsupported
     */
    public static LocalDate[] getPeriodBoundaries(
            LocalDate refDate,
            ColType colType,
            int offset,
            Integer rollingN,
            String rollingGrain) {

        LocalDate start;
        LocalDate end;

        switch (colType) {

            case WTD: {
                // ISO Week: Monday–Sunday window shifted by {@code offset} whole weeks, look back n weeks.
                LocalDate monday = refDate.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));
                LocalDate mondayOffset = monday.plusWeeks(offset);
                int n = (rollingN != null && rollingN > 0) ? rollingN : 1;
                start = mondayOffset.minusWeeks(n - 1);
                end   = (offset == 0) ? refDate : mondayOffset.plusDays(6);
                break;
            }

            case MTD: {
                // Month-to-date window shifted by {@code offset} months, look back n months.
                LocalDate targetMonthDate = refDate.plusMonths(offset);
                int n = (rollingN != null && rollingN > 0) ? rollingN : 1;
                start = targetMonthDate.withDayOfMonth(1).minusMonths(n - 1);
                if (offset == 0) {
                    end = refDate;
                } else {
                    end = targetMonthDate.with(TemporalAdjusters.lastDayOfMonth());
                }
                break;
            }

            case QTD: {
                // Quarter-to-date window shifted by {@code offset} quarters, look back n quarters.
                LocalDate targetQuarterDate = refDate.plusMonths(offset * 3);
                int n = (rollingN != null && rollingN > 0) ? rollingN : 1;
                int startMonthValue = ((targetQuarterDate.getMonthValue() - 1) / 3) * 3 + 1;
                start = LocalDate.of(targetQuarterDate.getYear(), startMonthValue, 1).minusMonths((n - 1) * 3);
                if (offset == 0) {
                    end = refDate;
                } else {
                    LocalDate qEndMonthDate = LocalDate.of(targetQuarterDate.getYear(), startMonthValue + 2, 1);
                    end = qEndMonthDate.with(TemporalAdjusters.lastDayOfMonth());
                }
                break;
            }

            case YTD: {
                // Year-to-date window shifted by {@code offset} years, look back n years.
                int yearShift = (Math.abs(offset) >= 12) ? offset / 12 : offset;
                LocalDate targetYearDate = refDate.plusYears(yearShift);
                int n = (rollingN != null && rollingN > 0) ? rollingN : 1;
                start = LocalDate.of(targetYearDate.getYear(), 1, 1).minusYears(n - 1);
                if (yearShift == 0) {
                    end = refDate;
                } else {
                    end = LocalDate.of(targetYearDate.getYear(), 12, 31);
                }
                break;
            }

            case ROLLING: {
                // Rolling lookback window whose grain is driven by {@code rollingGrain}.
                // N=1 is used as a safe default when the caller omits rollingN.
                int n = (rollingN != null) ? rollingN : 1;
                end = refDate;

                String grain = (rollingGrain != null && !rollingGrain.isBlank())
                    ? rollingGrain.trim().toUpperCase()
                    : "WEEK";  // backward-compat default

                switch (grain) {
                    case "DAY":
                        // N-day rolling: [refDate - N days + 1 day, refDate]
                        start = refDate.minusDays(n).plusDays(1);
                        break;
                    case "MONTH":
                        // N-month rolling: [refDate - N months + 1 day, refDate]
                        start = refDate.minusMonths(n).plusDays(1);
                        break;
                    case "WEEK":
                    default:
                        // N-week rolling (original behavior): [refDate - N weeks + 1 day, refDate]
                        start = refDate.minusWeeks(n).plusDays(1);
                        break;
                }
                break;
            }

            default:
                throw new IllegalArgumentException("Unsupported period type: " + colType);
        }

        return new LocalDate[]{start, end};
    }
}

